
% 2014-07-06
% Data input: file generated by the online platform
% Data output:
% 1. Information of participants: one row for each participant
% 2. Information of usual contacts: one row for each usual contact; each
% participant may have multiple rows
% 3. Details of contacts made on the assigned date: each participant may
% have multiple rows
clear all;
rawData = readtable('../0.1. data from POP/SPH_Contact2016_v2_POP_kleung_update_codes.xlsx');
codelabel = readtable('../0.1. data from POP/label_codelist_20160430.xlsx');

% Complete submissions
label = 'complete';
recIndex = [];
for ii = 1:length(rawData{:,1})
    if findstr(char(rawData.last_page(ii)),label)>0
        if isempty(recIndex)
            recIndex = ii;
        else
            recIndex = [recIndex,ii];
        end
    end
end
completeSub = rawData(recIndex,:);
completeSub = unique(completeSub);      
% Assume all records sent by POP are complete
completeSub = rawData;
% Find replicates of code
[codeCount,uniCode] = histcounts(completeSub.code,[unique(completeSub.code);max(unique(completeSub.code))+1]);
repCode = uniCode(codeCount>1);
repRow = completeSub(ismember(completeSub.code,repCode),:);

% Table 2.1:
% participant_code, residence_type
% num_usual_contacts
participant_code = completeSub.code;
% residence_type: 1 -- household  2 -- student hall  3 -- shared apartment
residence_type(isnan(completeSub.p3_1_2),1) = 9001;
residence_type(~isnan(completeSub.p3_1_2),1) = completeSub.p3_1_2(~isnan(completeSub.p3_1_2));
% number of usual contacts
num_usual_contacts(isnan(completeSub.p3_1_1),1) = 9001;
num_usual_contacts(~isnan(completeSub.p3_1_1),1) = completeSub.p3_1_1(~isnan(completeSub.p3_1_1));
usual_contact_general = table(participant_code,residence_type,num_usual_contacts);
writetable(usual_contact_general,'usual_contact_general.csv','Delimiter',',');

% Table 2.2:
% participant_code, residence_type
% num_usual_contacts
% unual_contact_idx, usual_age_or_range, usual_age_or_mid_range
% usual_gender, usual_relation
clear all;
rawData = readtable('../0.1. data from POP/SPH_Contact2016_v2_POP_kleung_update_codes.xlsx');
codelabel = readtable('../0.1. data from POP/label_codelist_20160430.xlsx');

% Complete submissions
label = 'complete';
recIndex = [];
for ii = 1:length(rawData{:,1})
    if findstr(char(rawData.last_page(ii)),label)>0
        if isempty(recIndex)
            recIndex = ii;
        else
            recIndex = [recIndex,ii];
        end
    end
end
completeSub = rawData(recIndex,:);
completeSub = unique(completeSub);      
% Assume all records sent by POP are complete
completeSub = rawData;
% Find replicates of code
[codeCount,uniCode] = histcounts(completeSub.code,[unique(completeSub.code);max(unique(completeSub.code))+1]);
repCode = uniCode(codeCount>1);
repRow = completeSub(ismember(completeSub.code,repCode),:);

numParticipant = length(completeSub{:,1});
usual_contact_general = readtable('usual_contact_general.csv');
kk = 0;
% Loop: index of participant
for ii = 1:numParticipant
    % from column p3_2_1_1_1 to p3_2_3_10
    iiRecord = completeSub(ii,39:88);
    % Loop: index of usual contacts (max. 10 usual contacts)
    for jj = 1:10
        if isnan(iiRecord{1,strcat('p3_2_1_1_',num2str(jj))})
            break;
        else
            kk = kk+1;
            participant_code(kk) = usual_contact_general.participant_code(ii);
            residence_type(kk) = usual_contact_general.residence_type(ii);
            num_usual_contacts(kk) = usual_contact_general.num_usual_contacts(ii);
            % usual contact index
            usual_contact_idx(kk) = jj;
            % age
            usual_age_or_range(kk) = iiRecord{1,strcat('p3_2_1_1_',num2str(jj))};
            if usual_age_or_range(kk)==1
                usual_age_or_mid_range(kk)= iiRecord{1,strcat('p3_2_1_2_',num2str(jj))};
                if isnan(usual_age_or_mid_range(kk))
                    usual_age_or_mid_range(kk)=9001;
                end
            else if usual_age_or_range(kk)==2
                    usual_age_or_mid_range(kk)= midAgeRange(codelabel,iiRecord{1,strcat('p3_2_1_3_',num2str(jj))});
                    if isnan(usual_age_or_mid_range(kk))
                        usual_age_or_mid_range(kk)=9001; 
                    end
                else
                    usual_age_or_mid_range(kk)=9001; 
                end
            end
            % gender
            usual_gender(kk) = iiRecord{1,strcat('p3_2_2_',num2str(jj))};
            if isnan(usual_gender(kk))
                usual_gender(kk)=9001;
            end
            % relationship
            usual_relation(kk) = iiRecord{1,strcat('p3_2_3_',num2str(jj))};
            if isnan(usual_relation(kk))
                usual_relation(kk) =9001;
            end
        end
    end
end

participant_code = participant_code';
residence_type = residence_type';
num_usual_contacts = num_usual_contacts';
usual_contact_idx = usual_contact_idx';
usual_age_or_range = usual_age_or_range';
usual_age_or_mid_range = usual_age_or_mid_range';
usual_gender = usual_gender';
usual_relation = usual_relation';

usual_contact_detail = ...
    table(participant_code, residence_type,num_usual_contacts,...
          usual_contact_idx, usual_age_or_range, usual_age_or_mid_range,...
          usual_gender, usual_relation);
writetable(usual_contact_detail,'usual_contact_detail.csv','Delimiter',',');