
% 2017-01-11
% Data input: file generated by the online platform
% Data output:
% 1. Information of participants: one row for each participant
% 2. Information of usual contacts: one row for each usual contact; each
% participant may have multiple rows
% 3. Details of contacts made on the assigned date: each participant may
% have multiple rows
clear all;
rawData = readtable('../0.1. data from POP/SPH_Contact2016_v2_POP_kleung_update_codes.xlsx');
codelabel = readtable('../0.1. data from POP/label_codelist_20160430.xlsx');
% Complete submissions
label = 'complete';
recIndex = [];
for ii = 1:length(rawData{:,1})
    if findstr(char(rawData.last_page(ii)),label)>0
        if isempty(recIndex)
            recIndex = ii;
        else
            recIndex = [recIndex,ii];
        end
    end
end
completeSub = rawData(recIndex,:);
completeSub = unique(completeSub);      
% Assume all records sent by POP are complete
completeSub = rawData;
% Find replicates of code
[codeCount,uniCode] = histcounts(completeSub.code,[unique(completeSub.code);max(unique(completeSub.code))+1]);
repCode = uniCode(codeCount>1);
repRow = completeSub(ismember(completeSub.code,repCode),:);

% Find online questionnaires to check
% participant_code
participant_code = completeSub.code;
% mode_survey: paper - 1; online - 2
mode_survey_raw = completeSub.mode;
mode_survey = zeros(length(mode_survey_raw),1);
mode_survey(strcmp(mode_survey_raw,'paper')==1) = 1;
mode_survey(strcmp(mode_survey_raw,'online')==1) = 2;
% time_first_access
time_first_access = datenum(completeSub.time_first_access,'yyyy-mm-dd HH:MM:SS');
time_last_update = datenum(completeSub.time_last_update,'yyyy-mm-dd HH:MM:SS');
duration_survey_hrs = 24*(time_last_update - time_first_access);
prospective_proxy = table(participant_code,mode_survey,...
    time_first_access,time_last_update,duration_survey_hrs);
writetable(prospective_proxy,'prospective_proxy.csv','Delimiter',',');