
% 2014-07-06
% Data input: file generated by the online platform
% Data output:
% 1. Information of participants: one row for each participant
% 2. Information of usual contacts: one row for each usual contact; each
% participant may have multiple rows
% 3. Details of contacts made on the assigned date: each participant may
% have multiple rows
clear all;
rawData = readtable('../0.1. data from POP/SPH_Contact2016_v2_POP_kleung_update_codes.xlsx');
codelabel = readtable('../0.1. data from POP/label_codelist_20160430.xlsx');

% Complete submissions
label = 'complete';
recIndex = [];
for ii = 1:length(rawData{:,1})
    if findstr(char(rawData.last_page(ii)),label)>0
        if isempty(recIndex)
            recIndex = ii;
        else
            recIndex = [recIndex,ii];
        end
    end
end
completeSub = rawData(recIndex,:);
completeSub = unique(completeSub);      
% Assume all records sent by POP are complete
completeSub = rawData;
% Find replicates of code
[codeCount,uniCode] = histcounts(completeSub.code,[unique(completeSub.code);max(unique(completeSub.code))+1]);
repCode = uniCode(codeCount>1);
repRow = completeSub(ismember(completeSub.code,repCode),:);

% Table 3.1: contact diary general
% participant_code, include_all_contacts, num_left_out, num_diary_contact
participant_code = completeSub.code;
include_all_contacts(isnan(completeSub.p5_1)) = 9001;
include_all_contacts(~isnan(completeSub.p5_1)) = completeSub.p5_1(~isnan(completeSub.p5_1));
include_all_contacts = include_all_contacts';
num_left_out = cell(size(participant_code));
num_left_out(strcmp(completeSub{:,'p5_1_2'},{''})) = {'9001'};
num_left_out(~strcmp(completeSub{:,'p5_1_2'},{''})) = completeSub{~strcmp(completeSub{:,'p5_1_2'},{''}),'p5_1_2'};
contact_diary_general = table(participant_code,include_all_contacts,num_left_out);
% writetable(contact_diary_general,'contact_diary_general.csv','Delimiter',',');
writetable(contact_diary_general,'contact_diary_general.xlsx');


% Table 3: contact diary
% participant_code, include_all_contacts
% diary_contact_idx
% contact_age_or_range, contact_age_or_mid_range
% contact_gender, contact_member
% skin_contact, non_physical_contact
% total_time
% house_contact, work_contact, school_contact, transport_contact, other_contact
% how_often
% last_update_time, last_update_date
clear all;
rawData = readtable('../0.1. data from POP/SPH_Contact2016_v2_POP_kleung_update_codes.xlsx');
codelabel = readtable('../0.1. data from POP/label_codelist_20160430.xlsx');

% Complete submissions
label = 'complete';
recIndex = [];
for ii = 1:length(rawData{:,1})
    if findstr(char(rawData.last_page(ii)),label)>0
        if isempty(recIndex)
            recIndex = ii;
        else
            recIndex = [recIndex,ii];
        end
    end
end
completeSub = rawData(recIndex,:);
completeSub = unique(completeSub);      
% Assume all records sent by POP are complete
completeSub = rawData;
% Find replicates of code
[codeCount,uniCode] = histcounts(completeSub.code,[unique(completeSub.code);max(unique(completeSub.code))+1]);
repCode = uniCode(codeCount>1);
repRow = completeSub(ismember(completeSub.code,repCode),:);
numParticipant = height(completeSub);
contact_diary_general = readtable('contact_diary_general_kleung_relabel.xlsx');

% day 0
day0 = datenum('2015-01-01','yyyy-mm-dd');
kk = 0;
% Loop: index of participant
for ii = 1:numParticipant
    % from column cd_1_name_1 to cd_3_3_100
    iiRecord = completeSub(ii,92:1791);
    display(['Participant: ',num2str(ii)]);
    % Loop: index of contacts (max. 100 in contact diary)
    for jj = 1:100
        if ( isnan(iiRecord{1,strcat('cd_1_2_0_',num2str(jj))}) && isnan(iiRecord{1,strcat('cd_1_3_',num2str(jj))}))
            num_diary_contacts(ii) = jj-1;
            break;
        else
            kk = kk+1;
            participant_code(kk) = contact_diary_general.participant_code(ii);
            include_all_contacts(kk) = contact_diary_general.include_all_contacts(ii);
            % diary contact index
            diary_contact_idx(kk) = jj;
            % age
            contact_age_or_range(kk) = iiRecord{1,strcat('cd_1_2_0_',num2str(jj))};
            if contact_age_or_range(kk)==1
                contact_age_or_mid_range(kk)=iiRecord{1,strcat('cd_1_2_1_',num2str(jj))};
                if isnan(contact_age_or_mid_range(kk))
                    contact_age_or_mid_range(kk) = 9001;
                end
            else if contact_age_or_range(kk)==2
                    contact_age_or_mid_range(kk)=midAgeRange(codelabel,iiRecord{1,strcat('cd_1_2_2_',num2str(jj))});
                    if isnan(contact_age_or_mid_range(kk))
                        contact_age_or_mid_range(kk) = 9001; 
                    end
                else if isnan(contact_age_or_range(kk))
                        contact_age_or_mid_range(kk) = 9001;
                    end
                end
            end
            
            %contact_gender
            contact_gender(kk) = iiRecord{1,strcat('cd_1_3_',num2str(jj))};
            if isnan(contact_gender(kk))
                contact_gender(kk)=9001;
            end
            %contact_member
            contact_member(kk) = iiRecord{1,strcat('cd_1_4_',num2str(jj))};
            if isnan(contact_member(kk))
                contact_member(kk)=9001;
            end
            
            %skin_contact
            skin_contact(kk) = iiRecord{1,strcat('cd_2_1_1_',num2str(jj))};
            if isnan(skin_contact(kk))
                skin_contact(kk)=9001;
            end
            %non_physical_contact
            non_physical_contact(kk) = iiRecord{1,strcat('cd_2_1_2_',num2str(jj))};
            if isnan(non_physical_contact(kk))
                non_physical_contact(kk)=9001;
            end
            %total_time
            total_time(kk) = iiRecord{1,strcat('cd_2_2_',num2str(jj))};
            if isnan(total_time(kk))
                total_time(kk)=9001;
            end
            
            % house_contact, work_contact, school_contact, transport_contact, other_contact
            house_contact(kk) = iiRecord{1,strcat('cd_2_3_1_',num2str(jj))};
            if isnan(house_contact(kk))
                house_contact(kk)=9001;
            end
            work_contact(kk) = iiRecord{1,strcat('cd_2_3_2_',num2str(jj))};
            if isnan(work_contact(kk))
                work_contact(kk)=9001;
            end
            school_contact(kk) = iiRecord{1,strcat('cd_2_3_3_',num2str(jj))};
            if isnan(school_contact(kk))
                school_contact(kk)=9001;
            end
            transport_contact(kk) = iiRecord{1,strcat('cd_2_3_4_',num2str(jj))};
            if isnan(transport_contact(kk))
                transport_contact(kk)=9001;
            end
            other_contact(kk) = iiRecord{1,strcat('cd_2_3_5_',num2str(jj))};
            if isnan(other_contact(kk))
                other_contact(kk)=9001;
            end
            % how_often
            how_often(kk) = iiRecord{1,strcat('cd_3_2_',num2str(jj))};
            if isnan(how_often(kk))
                how_often(kk)=9001;
            end
            % record time
            if strcmp(iiRecord{1,strcat('cd_3_1_',num2str(jj))},'')
                record_time(kk) = 9001;
            else
                record_time(kk) = datenum(iiRecord{1,strcat('cd_3_1_',num2str(jj))},'HH:MM');
            end
            % record date
            if strcmp(iiRecord{1,strcat('cd_3_3_',num2str(jj))},'')
                record_date(kk) = 9001;
            else
                record_date(kk) = datenum(iiRecord{1,strcat('cd_3_3_',num2str(jj))},'yyyy-mm-dd')-day0;
            end
        end
    end
end
% Table 3.1: contact diary general
% participant_code, include_all_contacts, num_left_out, num_diary_contact
contact_diary_general = readtable('contact_diary_general_kleung_relabel.xlsx');
contact_diary_general = table(contact_diary_general.participant_code,contact_diary_general.include_all_contacts,contact_diary_general.num_left_out,num_diary_contacts',...
    'VariableNames',{'participant_code' 'include_all_contacts' 'num_left_out' 'num_diary_contact'});
% Table 3.2
contact_diary_detail = table(participant_code', include_all_contacts',...
diary_contact_idx',...
contact_age_or_range', contact_age_or_mid_range',...
contact_gender', contact_member',...
skin_contact', non_physical_contact',...
total_time',...
house_contact', work_contact', school_contact', transport_contact', other_contact',...
how_often',...
record_time',record_date',...
'VariableNames',...
{'participant_code', 'include_all_contacts',...
'diary_contact_idx',...
'contact_age_or_range', 'contact_age_or_mid_range',...
'contact_gender', 'contact_member',...
'skin_contact', 'non_physical_contact',...
'total_time',...
'house_contact', 'work_contact', 'school_contact', 'transport_contact', 'other_contact',...
'how_often',...
'record_time','record_date'});

writetable(contact_diary_general,'contact_diary_general.csv','Delimiter',',');
writetable(contact_diary_general,'contact_diary_general.xlsx');
writetable(contact_diary_detail,'contact_diary_detail.csv','Delimiter',',');

