
% 2015-04-16
% Data input: file generated by the online platform
% Data output:
% 1. Information of participants: one row for each participant
% 2. Information of usual contacts: one row for each usual contact; each
% participant may have multiple rows
% 3. Details of contacts made on the assigned date: each participant may
% have multiple rows
clear all;
rawData = readtable('../0.1. data from POP/SPH_Contact2016_v2_POP_kleung_update_codes.xlsx');
codelabel = readtable('../0.1. data from POP/label_codelist_20160430.xlsx');
% Complete submissions
label = 'complete';
recIndex = [];
for ii = 1:length(rawData{:,1})
    if findstr(char(rawData.last_page(ii)),label)>0
        if isempty(recIndex)
            recIndex = ii;
        else
            recIndex = [recIndex,ii];
        end
    end
end
completeSub = rawData(recIndex,:);
completeSub = unique(completeSub);      
% Assume all records sent by POP are complete
completeSub = rawData;
% Find replicates of code
[codeCount,uniCode] = histcounts(completeSub.code,[unique(completeSub.code);max(unique(completeSub.code))+1]);
repCode = uniCode(codeCount>1);
repRow = completeSub(ismember(completeSub.code,repCode),:);

% Table 1:
% participant_code, mode_survey
% assign_date, actual_date, age_or_range, age_or_mid_range, gender,
% full_or_part_time, work_role, edu, indiv_or_family_income, income_mid_range,
% place_birth, district, ethinicity

% participant_code
participant_code = completeSub.code;
% mode_survey: paper - 1; online - 2
mode_survey_raw = completeSub.mode;
mode_survey = zeros(length(mode_survey_raw),1);
mode_survey(strcmp(mode_survey_raw,'paper')==1) = 1;
mode_survey(strcmp(mode_survey_raw,'online')==1) = 2;
% day 0
day0 = datenum('2015-01-01','yyyy-mm-dd');
% assign_date:
assign_date_raw = completeSub.assigned_date;
assign_date = datenum(assign_date_raw,'yyyy-mm-dd')-day0;
assign_week_day = weekday(datenum(assign_date_raw,'yyyy-mm-dd'));
% actual_date:
actual_date_raw = completeSub.time_last_update;
actual_date = datenum(actual_date_raw,'yyyy-mm-dd HH:MM:SS')-day0;
actual_week_day = weekday(datenum(actual_date_raw,'yyyy-mm-dd HH:MM:SS'));
actual_hour = hour(datenum(actual_date_raw,'yyyy-mm-dd HH:MM:SS'));
% age_or_range: age --1, age_range -- 2
age_or_range = completeSub.p2_1_1;
age_or_mid_range(age_or_range == 1,1) = completeSub.p2_1_2(age_or_range==1);
age_or_mid_range(age_or_range == 2,1) = midAgeRange(codelabel,completeSub.p2_1_3(age_or_range==2));
% gender: male -- 1; female -- 2
gender = completeSub.p2_2;
% full_or_part_time: full time --1; part time --2; unwilling/unavailable --999; empty--9001
full_or_part_time = completeSub.p2_3_1;
% work_role: employee --1; employer --2; self-employed --3; students --4;
% homemakers --5; retired --6; others -- 997; don't know --998
% unwilling/unavailable --999;
work_role(isnan(completeSub.p2_3_2),1) = 9001;
work_role(~isnan(completeSub.p2_3_2),1) = completeSub.p2_3_2(~isnan(completeSub.p2_3_2));
% edu: primary or below --1; secondary --2; post-secondary --3; others--997;
% don't know -- 998; unwilling/unavailable --999;
edu = completeSub.p2_4;
% indiv_or_family_income: individual --1; household --2; unwilling/unavailable --999;
indiv_or_family_income = completeSub.p2_5_1;
% income_mid_range
income_mid_range(isnan(completeSub.p2_5_2),1) = 9001;
income_mid_range(~isnan(completeSub.p2_5_2),1) = completeSub.p2_5_2(~isnan(completeSub.p2_5_2));
% place_birth: Hong Kong --1; Mainland China --2; others --997; don't know --998
place_birth = completeSub.p2_6;
% district
district = completeSub.p2_7;
% ethinicity
ethnicity = completeSub.p2_8;
% permanent_residence
permanent_residence = completeSub.p2_9;

% Table 1: demographics
demographics = table(participant_code,mode_survey,...
    assign_date,assign_week_day,...
    actual_date,actual_week_day,actual_hour,...
    age_or_range,age_or_mid_range,gender,...
    full_or_part_time,work_role,edu,indiv_or_family_income,income_mid_range,...
    place_birth,district,ethnicity,permanent_residence);
demographics = unique(demographics);
writetable(demographics,'demographics.csv','Delimiter',',');


