function out = mcmcRes_RSV_intervention(x0,...
    indicesMonthlyRSV,...
    stateM,...
    stateS0, stateS1, stateS2, stateS3,...
    stateE0, stateE1, stateE2, stateE3,...
    stateI0, stateI1, stateI2, stateI3,...
    stateA0, stateA1, stateA2, stateA3,...
    stateR0, stateR1, stateR2, stateR3,...
    stateZ,...
    stateVmab1,stateVmab2,stateVmvax1,stateVmvax2,stateVpvax1,stateVpvax2,...
    totalPopulation, ageGroupDefRangeAll, muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr, conversationContactMatr,...
    dateZero,dateStart,~, numDays, numTimeSteps, dt,...
    mAbCoverageIter,mAbEffectivenessIter,mAbDuration,...
    mVaxCoverageIter,mVaxEffectivenessIter,mVaxDuration,...
    oVaxCoverageIter,oVaxEffectivenessIter,oVaxDuration)

% Parameters in Table 1 (to be estimated)
% Average duration of maternally derived immunity (days)
xiMaternalImmunity = x0(1);
% Average duration of post-infection immunity (days)
omegaInfectionImmunity = x0(2);
% Average duration of exposure (days)
sigmaExposure = x0(3);
% Average duration of primary infection (days)
gammaZeroPrimaryInfection = x0(4);
% Decrease in secondary infection duration relative to primary
g1ReductionInfectiousDuration = x0(5);
% Decrease in subsequent infection duration relative to secondary
g2ReductionInfectiousDuration = x0(6);
% Susceptibility
% Secondary infection relative to primary
delta1RelSuscep = x0(7);
% 3rd infection relative to 2nd
delta2RelSuscep = x0(8);
% Subsequent infections relative to 3rd
delta3RelSuscep = x0(9);
% Proportion asymptomatic (<1 yr, 1-4 yr, 5-14 yr, and 15+ yr)
pAsym = x0(10:13);
% Relative reduction in infectiousness for asymptomatic infections
alphaReductionInfectiousness = x0(14);
% Probability of RSV transmission per physical contact
qTransmissPhysical = x0(15);
% Relative reduction in probability of RSV transmission per conversational contact compared to physical contact
qTransmissConversation = 1;
% Relative amplitude of transmission during peak
b1AmpTransmissPeak = x0(16);
% Seasonal shift in transmission
phiSeasonalShift = x0(17);
% Seasonal wavelength constant
psiSeasonalWavelength = x0(18);
% Seed
% Initial proportion (at t = 0) of people who are infected (i.e. in epidemiological compartments E, I or A) with RSV
iniInfectiousProp = x0(19);
% Initial proportion (at t = 0) of people who not-infected but are protected (in epidemiological compartment R) from RSV
iniRecoveredProp = x0(20);

% Probability that an RSV infection is reported (0-4 yr; 5-54 yr; 55+ yr)
expReport = [x0(21), x0(22)];
epsilonReport17 = x0(23);
epsilonReport18 = x0(24);
epsilonReport19 = x0(25);
epsilonReport20 = x0(26);
epsilonReport21 = x0(27);

% Seropositive probability of RSV infected S E I A
probSeropos = x0(28);

outSEIR_intervention = age_SEIR_RSV_intervention(...
    stateM,...
    stateS0,stateS1,stateS2,stateS3,...
    stateE0,stateE1,stateE2,stateE3,...
    stateI0,stateI1,stateI2,stateI3,...
    stateA0,stateA1,stateA2,stateA3,...
    stateR0,stateR1,stateR2,stateR3,...
    stateZ,...
    stateVmab1,stateVmab2,stateVmvax1,stateVmvax2,stateVpvax1,stateVpvax2,...
    mAbCoverageIter,mAbEffectivenessIter,mAbDuration,...
    mVaxCoverageIter,mVaxEffectivenessIter,mVaxDuration,...
    oVaxCoverageIter,oVaxEffectivenessIter,oVaxDuration,...
    totalPopulation,ageGroupDefRangeAll,muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr,conversationContactMatr,...
    iniInfectiousProp, iniRecoveredProp,...
    dateZero,dateStart,numDays,numTimeSteps,dt,...
    xiMaternalImmunity,omegaInfectionImmunity,sigmaExposure,...
    gammaZeroPrimaryInfection,g1ReductionInfectiousDuration,g2ReductionInfectiousDuration,...
    delta1RelSuscep,delta2RelSuscep,delta3RelSuscep,...
    pAsym,alphaReductionInfectiousness,...
    qTransmissPhysical,qTransmissConversation,...
    b1AmpTransmissPeak,phiSeasonalShift,psiSeasonalWavelength,probSeropos);

outSEIR_no_intervention = age_SEIR_RSV_intervention(...
    stateM,...
    stateS0,stateS1,stateS2,stateS3,...
    stateE0,stateE1,stateE2,stateE3,...
    stateI0,stateI1,stateI2,stateI3,...
    stateA0,stateA1,stateA2,stateA3,...
    stateR0,stateR1,stateR2,stateR3,...
    stateZ,...
    stateVmab1,stateVmab2,stateVmvax1,stateVmvax2,stateVpvax1,stateVpvax2,...
    0*mAbCoverageIter,mAbEffectivenessIter,mAbDuration,...
    0*mVaxCoverageIter,mVaxEffectivenessIter,mVaxDuration,...
    0*oVaxCoverageIter,oVaxEffectivenessIter,oVaxDuration,...
    totalPopulation,ageGroupDefRangeAll,muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr,conversationContactMatr,...
    iniInfectiousProp, iniRecoveredProp,...
    dateZero,dateStart,numDays,numTimeSteps,dt,...
    xiMaternalImmunity,omegaInfectionImmunity,sigmaExposure,...
    gammaZeroPrimaryInfection,g1ReductionInfectiousDuration,g2ReductionInfectiousDuration,...
    delta1RelSuscep,delta2RelSuscep,delta3RelSuscep,...
    pAsym,alphaReductionInfectiousness,...
    qTransmissPhysical,qTransmissConversation,...
    b1AmpTransmissPeak,phiSeasonalShift,psiSeasonalWavelength,probSeropos);

numAgeGroups = length(totalPopulation);

epsilonReportArr = exp(expReport(1)+expReport(2)*ageGroupDefRangeAll(1:(find(ageGroupDefRangeAll==2)-1)));
epsilonByAge = [...
    epsilonReportArr,...
    repmat(epsilonReport17,1,find(ageGroupDefRangeAll==5)-find(ageGroupDefRangeAll==2)),...
    repmat(epsilonReport18,1,find(ageGroupDefRangeAll==15)-find(ageGroupDefRangeAll==5)),...
    repmat(epsilonReport19,1,find(ageGroupDefRangeAll==55)-find(ageGroupDefRangeAll==15)),...
    repmat(epsilonReport20,1,find(ageGroupDefRangeAll==75)-find(ageGroupDefRangeAll==55)),...
    repmat(epsilonReport21,1,numAgeGroups-find(ageGroupDefRangeAll==75)+1)];

% Daily incidence
dayIndices = reshape(1:numTimeSteps, [], numDays)';
dailyAgeSpecificIncidence_intervention = zeros(numDays, numAgeGroups);
dailyAgeSpecificIncidence_no_intervention = zeros(numDays, numAgeGroups);
dailyAgeSpecificIncidenceReportInterventionAverted = zeros(numDays, numAgeGroups);
dailyAgeSpecificIncidenceReport_no_intervention_rec = zeros(numDays, numAgeGroups);
dailyAgeSpecificIncidenceReport_with_intervention_rec = zeros(numDays, numAgeGroups);

% Intervention
for iiDay = 1:numDays
    dailyAgeSpecificIncidence_intervention(iiDay,:) = sum(outSEIR_intervention.stateZ(dayIndices(iiDay,:),:), 1);
    dailyAgeSpecificIncidence_no_intervention(iiDay,:) = sum(outSEIR_no_intervention.stateZ(dayIndices(iiDay,:),:), 1);
    % With intervention
    dailyAgeSpecificIncidenceReport_intervention = sum(outSEIR_intervention.stateZ(dayIndices(iiDay,:),:), 1).*epsilonByAge;
    % No intervention
    dailyAgeSpecificIncidenceReport_no_intervention = sum(outSEIR_no_intervention.stateZ(dayIndices(iiDay,:),:), 1).*epsilonByAge;
    % Averted
    dailyAgeSpecificIncidenceReport_no_intervention_rec(iiDay,:) = dailyAgeSpecificIncidenceReport_no_intervention;
    dailyAgeSpecificIncidenceReport_with_intervention_rec(iiDay,:) = dailyAgeSpecificIncidenceReport_intervention;
    dailyAgeSpecificIncidenceReportInterventionAverted(iiDay,:) = dailyAgeSpecificIncidenceReport_no_intervention - dailyAgeSpecificIncidenceReport_intervention;
end

dailyAgeSpecificIncidenceGroup_intervention = [...
    sum(dailyAgeSpecificIncidence_intervention(:,1:(indicesMonthlyRSV(1)-1)),2),...
    sum(dailyAgeSpecificIncidence_intervention(:,indicesMonthlyRSV(1):(indicesMonthlyRSV(2)-1)),2),...
    sum(dailyAgeSpecificIncidence_intervention(:,indicesMonthlyRSV(2):(indicesMonthlyRSV(3)-1)),2),...
    sum(dailyAgeSpecificIncidence_intervention(:,indicesMonthlyRSV(3):(indicesMonthlyRSV(4)-1)),2),...
    sum(dailyAgeSpecificIncidence_intervention(:,indicesMonthlyRSV(4):(indicesMonthlyRSV(5)-1)),2),...
    sum(dailyAgeSpecificIncidence_intervention(:,indicesMonthlyRSV(5):(indicesMonthlyRSV(6)-1)),2)];
dailyAgeSpecificIncidenceGroup_no_intervention = [...
    sum(dailyAgeSpecificIncidence_no_intervention(:,1:(indicesMonthlyRSV(1)-1)),2),...
    sum(dailyAgeSpecificIncidence_no_intervention(:,indicesMonthlyRSV(1):(indicesMonthlyRSV(2)-1)),2),...
    sum(dailyAgeSpecificIncidence_no_intervention(:,indicesMonthlyRSV(2):(indicesMonthlyRSV(3)-1)),2),...
    sum(dailyAgeSpecificIncidence_no_intervention(:,indicesMonthlyRSV(3):(indicesMonthlyRSV(4)-1)),2),...
    sum(dailyAgeSpecificIncidence_no_intervention(:,indicesMonthlyRSV(4):(indicesMonthlyRSV(5)-1)),2),...
    sum(dailyAgeSpecificIncidence_no_intervention(:,indicesMonthlyRSV(5):(indicesMonthlyRSV(6)-1)),2)];

populationAgeGroup = [...
    sum(totalPopulation(1:(indicesMonthlyRSV(1)-1))),...
    sum(totalPopulation(indicesMonthlyRSV(1):(indicesMonthlyRSV(2)-1))),...
    sum(totalPopulation(indicesMonthlyRSV(2):(indicesMonthlyRSV(3)-1))),...
    sum(totalPopulation(indicesMonthlyRSV(3):(indicesMonthlyRSV(4)-1))),...
    sum(totalPopulation(indicesMonthlyRSV(4):(indicesMonthlyRSV(5)-1))),...
    sum(totalPopulation(indicesMonthlyRSV(5):(indicesMonthlyRSV(6)-1)))];

out = struct();
out.outSEIR_intervention = outSEIR_intervention;
out.outSEIR_no_intervention = outSEIR_no_intervention;
out.dailyAgeSpecificIncidenceGroup_intervention = dailyAgeSpecificIncidenceGroup_intervention;
out.dailyAgeSpecificIncidenceGroup_no_intervention = dailyAgeSpecificIncidenceGroup_no_intervention;

out.populationAgeGroup = populationAgeGroup;
out.epsilonByAge = epsilonByAge;

out.dailyAgeSpecificIncidenceReportInterventionAverted = dailyAgeSpecificIncidenceReportInterventionAverted;
out.dailyAgeSpecificIncidenceReport_no_intervention_rec = dailyAgeSpecificIncidenceReport_no_intervention_rec;
out.dailyAgeSpecificIncidenceReport_with_intervention_rec = dailyAgeSpecificIncidenceReport_with_intervention_rec;

end