function interTable = saveIntermediateStateVariables(stateM,...
    stateS0, stateS1, stateS2, stateS3,...
    stateE0, stateE1, stateE2, stateE3,...
    stateI0, stateI1, stateI2, stateI3,...
    stateA0, stateA1, stateA2, stateA3,...
    stateR0, stateR1, stateR2, stateR3,...
    totalPopulation, muBirthRate, propAliveDaily,etaMortalityRate,...
    xiMaternalImmunity, omegaInfectionImmunity, sigmaExposure,...
    gammaZeroPrimaryInfection, g1ReductionInfectiousDuration, g2ReductionInfectiousDuration,...
    delta1RelSuscep, delta2RelSuscep, delta3RelSuscep,pMaternalProtection,muBirthIndicator,agingIndicator,pAsym_arr,tStep,lambda_no_deltaSusp)

interTable = [
    pMaternalProtection.*(muBirthRate(1).* muBirthIndicator);...
    - xiMaternalImmunity * stateM(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateM(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateM(tStep, 1:(end-1))].*agingIndicator;...
    -stateM(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    (1-pMaternalProtection).*(muBirthRate(1).* muBirthIndicator);...
    + xiMaternalImmunity * stateM(tStep, :);...
    - lambda_no_deltaSusp .* stateS0(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateS0(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateS0(tStep, 1:(end-1))].*agingIndicator;...
    -stateS0(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    lambda_no_deltaSusp .* stateS0(tStep, :);...
    - sigmaExposure * stateE0(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateE0(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateE0(tStep, 1:(end-1))].*agingIndicator;...
    -stateE0(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    sigmaExposure * pAsym_arr.* stateE0(tStep, :);...
    - gammaZeroPrimaryInfection * stateA0(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateA0(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateA0(tStep, 1:(end-1))].*agingIndicator;...
    -stateA0(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    sigmaExposure * (1 - pAsym_arr).* stateE0(tStep, :);...
    - gammaZeroPrimaryInfection * stateI0(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateI0(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateI0(tStep, 1:(end-1))].*agingIndicator;...
    - stateI0(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    gammaZeroPrimaryInfection * (stateA0(tStep, :) + stateI0(tStep, :));...
    - omegaInfectionImmunity * stateR0(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateR0(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateR0(tStep, 1:(end-1))].*agingIndicator;...
    - stateR0(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    omegaInfectionImmunity * stateR0(tStep, :);...
    - delta1RelSuscep * lambda_no_deltaSusp .* stateS1(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateS1(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateS1(tStep, 1:(end-1))].*agingIndicator;...
    - stateS1(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    delta1RelSuscep * lambda_no_deltaSusp .* stateS1(tStep, :);...
    - sigmaExposure * stateE1(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateE1(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateE1(tStep, 1:(end-1))].*agingIndicator;...
    - stateE1(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    sigmaExposure * pAsym_arr.* stateE1(tStep, :);...
    - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration * stateA1(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateA1(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateA1(tStep, 1:(end-1))].*agingIndicator;...
    - stateA1(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    sigmaExposure * (1 - pAsym_arr).* stateE1(tStep, :);...
    - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration * stateI1(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateI1(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateI1(tStep, 1:(end-1))].*agingIndicator;...
    - stateI1(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    gammaZeroPrimaryInfection / g1ReductionInfectiousDuration * (stateA1(tStep, :) + stateI1(tStep, :));...
    - omegaInfectionImmunity * stateR1(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateR1(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateR1(tStep, 1:(end-1))].*agingIndicator;...
    - stateR1(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    omegaInfectionImmunity * stateR1(tStep, :);...
    - delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS2(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateS2(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateS2(tStep, 1:(end-1))].*agingIndicator;...
    - stateS2(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS2(tStep, :);...
    - sigmaExposure * stateE2(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateE2(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateE2(tStep, 1:(end-1))].*agingIndicator;...
    -stateE2(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    sigmaExposure * pAsym_arr.* stateE2(tStep, :);...
    - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateA2(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateA2(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateA2(tStep, 1:(end-1))].*agingIndicator;...
    - stateA2(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...


    sigmaExposure * (1 - pAsym_arr).* stateE2(tStep, :);...
    - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateI2(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateI2(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateI2(tStep, 1:(end-1))].*agingIndicator;...
    - stateI2(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * (stateA2(tStep, :) + stateI2(tStep, :));...
    - omegaInfectionImmunity * stateR2(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateR2(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateR2(tStep, 1:(end-1))].*agingIndicator;...
    - stateR2(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    omegaInfectionImmunity * stateR2(tStep, :);...
    - delta3RelSuscep * delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS3(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateS3(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateS3(tStep, 1:(end-1))].*agingIndicator;...
    - stateS3(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    delta3RelSuscep * delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS3(tStep, :);...
    - sigmaExposure * stateE3(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateE3(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateE3(tStep, 1:(end-1))].*agingIndicator;...
    - stateE3(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...
    
    sigmaExposure * pAsym_arr.* stateE3(tStep, :);...
    - gammaZeroPrimaryInfection  / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateA3(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateA3(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateA3(tStep, 1:(end-1))].*agingIndicator;...
    - stateA3(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    sigmaExposure * (1 - pAsym_arr).* stateE3(tStep, :);...
    - gammaZeroPrimaryInfection  / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateI3(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateI3(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateI3(tStep, 1:(end-1))].*agingIndicator;...
    - stateI3(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily);...

    gammaZeroPrimaryInfection  / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * (stateA3(tStep, :) + stateI3(tStep, :));...
    - omegaInfectionImmunity * stateR3(tStep, :);...
    - [etaMortalityRate(1:(end-1)).* stateR3(tStep, 1:(end-1)),0];...
    + [0,etaMortalityRate(1:(end-1)).* stateR3(tStep, 1:(end-1))].*agingIndicator;...
    -stateR3(tStep, :).*(1-muBirthRate(2)/sum(totalPopulation)-propAliveDaily)];

end