function [c, ceq] = parameterConstraint(x0)

% pAsym
pAsym = x0(10:13);

% Probability that an RSV infection is reported (0-4 yr; 5-54 yr; 55+ yr)
expReport = [x0(22), x0(23)];

c = [...
    pAsym(1)-pAsym(2),...
    pAsym(2)-pAsym(3),...
    pAsym(3)-pAsym(4),...
    -exp(expReport(1)+expReport(2)),...
    exp(expReport(1)+expReport(2))-1,...
    -exp(expReport(1)+ 5*expReport(2)),...
    exp(expReport(1)+expReport(2))-1];

ceq = [];

end

