function [sumLogL,logLArr] = logLikelihood_RSV(x0,...
    monthlyILICaseRSV,ageDefMonthlyRSV,...
    seroprevData,indicesSeroPreg,indicesSeroAge,...
    seroprevDataMeta,indicesSeroAgeMeta,...
    seroprevDataHKRec,indicesSeroAgeHK,...
    dataPitzerIncubation, dataPitzerInfectious,...
    stateM,...
    stateS0, stateS1, stateS2, stateS3,...
    stateE0, stateE1, stateE2, stateE3,...
    stateI0, stateI1, stateI2, stateI3,...
    stateA0, stateA1, stateA2, stateA3,...
    stateR0, stateR1, stateR2, stateR3,...
    stateZ,...
    probVmAb, probVvax,...
    totalPopulation, ageGroupDefRangeAll, muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr, conversationContactMatr,...
    dateZero,dateStart,cutoffCOVID, numDays, numTimeSteps, dt)

if numel(x0) ~= 28
    error('logLikelihood_RSV expects a 28-parameter vector.');
end

% x0 contains the estimated parameters; fixed parameters are declared
% explicitly below.
% Average duration of maternally derived immunity (days)
xiMaternalImmunity = 1/90;
% Average duration of post-infection immunity (days)
omegaInfectionImmunity = x0(1);
% Average duration of exposure (days)
sigmaExposure = x0(2);
% Average duration of primary infection (days)
gammaZeroPrimaryInfection = x0(3);
% Decrease in secondary infection duration relative to primary
g1ReductionInfectiousDuration = x0(4);
% Decrease in subsequent infection duration relative to secondary
g2ReductionInfectiousDuration = x0(5);
% Susceptibility
% Secondary infection relative to primary
delta1RelSuscep = x0(6);
% 3rd infection relative to 2nd
delta2RelSuscep = x0(7);
% Subsequent infections relative to 3rd
delta3RelSuscep = x0(8);
% Proportion asymptomatic (<1 yr, 1-4 yr, 5-14 yr, and 15+ yr)
pAsym = x0(9:12);
% Relative reduction in infectiousness for asymptomatic infections
alphaReductionInfectiousness = x0(13);
% Probability of RSV transmission per physical contact
qTransmissPhysical = x0(14);
% Relative transmission multiplier for conversational contacts; fixed to 1
% in this likelihood.
qTransmissConversation = 1;
% Relative amplitude of transmission during peak
b1AmpTransmissPeak = x0(15);
% Seasonal shift in transmission
phiSeasonalShift = x0(16);
% Seasonal wavelength constant
psiSeasonalWavelength = x0(17);
% Seed
% Initial proportion (at t = 0) of people who are infected (i.e. in epidemiological compartments E, I or A) with RSV
iniInfectiousProp = x0(18);
% Initial proportion (at t = 0) of people who not-infected but are protected (in epidemiological compartment R) from RSV
iniRecoveredProp = x0(19);

% Reporting parameters: expReport applies to ages 0-23 months, and the
% epsilon parameters apply to ages 2-4, 5-14, 15-54, 55-74, and 75+ years.
expReport = [x0(20), x0(21)];
epsilonReport17 = x0(22);
epsilonReport18 = x0(23);
epsilonReport19 = x0(24);
epsilonReport20 = x0(25);
epsilonReport21 = x0(26);

% Seropositive probability of RSV infected S E I A
probSeropos = x0(27);
% Linear overdispersion parameter for monthly RSV case counts.
% This keeps extra-Poisson variation even when monthly means are small.
linDispMonthlyReport = x0(28);

outSEIR = age_SEIR_RSV_mex(...
    stateM,...
    stateS0,stateS1,stateS2,stateS3,...
    stateE0,stateE1,stateE2,stateE3,...
    stateI0,stateI1,stateI2,stateI3,...
    stateA0,stateA1,stateA2,stateA3,...
    stateR0,stateR1,stateR2,stateR3,...
    stateZ,...
    probVmAb, probVvax,...
    totalPopulation,ageGroupDefRangeAll,muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr,conversationContactMatr,...
    iniInfectiousProp, iniRecoveredProp,...
    dateZero,dateStart,numDays,numTimeSteps,dt,...
    xiMaternalImmunity,omegaInfectionImmunity,sigmaExposure,...
    gammaZeroPrimaryInfection,g1ReductionInfectiousDuration,g2ReductionInfectiousDuration,...
    delta1RelSuscep,delta2RelSuscep,delta3RelSuscep,...
    pAsym,alphaReductionInfectiousness,...
    qTransmissPhysical,qTransmissConversation,...
    b1AmpTransmissPeak,phiSeasonalShift,psiSeasonalWavelength,probSeropos);

numAgeGroups = length(totalPopulation);

% Likelihood for incubation period
logLIncubation = log(exppdf(dataPitzerIncubation,1/sigmaExposure));
logLIncubation(logLIncubation==-Inf) = -1e9;
logLIncubation(isnan(logLIncubation)) = -1e9;
% Likelihood for infectious period
logLInfectious = [
    log(exppdf(dataPitzerInfectious.children,1/gammaZeroPrimaryInfection));
    log(exppdf(dataPitzerInfectious.adult,1/(gammaZeroPrimaryInfection/g1ReductionInfectiousDuration/g2ReductionInfectiousDuration)))];
logLInfectious(logLInfectious==-Inf) = -1e9;
logLInfectious(isnan(logLInfectious)) = -1e9;

% Daily incidence
dayIndices = reshape(1:numTimeSteps, [], numDays)';
dailyAgeSpecificIncidence = zeros(numDays, numAgeGroups);
for iiDay = 1:numDays
    dailyAgeSpecificIncidence(iiDay,:) = sum(outSEIR.stateZ(dayIndices(iiDay,:),:), 1);
end

% Age-specific reporting probabilities by model age group.
epsilonReportArr = exp(expReport(1)+expReport(2)*ageGroupDefRangeAll(1:(find(ageGroupDefRangeAll==2)-1)));
epsilonByAge = [...
    epsilonReportArr,...
    repmat(epsilonReport17,1,find(ageGroupDefRangeAll==5)-find(ageGroupDefRangeAll==2)),...
    repmat(epsilonReport18,1,find(ageGroupDefRangeAll==15)-find(ageGroupDefRangeAll==5)),...
    repmat(epsilonReport19,1,find(ageGroupDefRangeAll==55)-find(ageGroupDefRangeAll==15)),...
    repmat(epsilonReport20,1,find(ageGroupDefRangeAll==75)-find(ageGroupDefRangeAll==55)),...
    repmat(epsilonReport21,1,numAgeGroups-find(ageGroupDefRangeAll==75)+1)];

% Likelihood for monthly case counts: negative binomial applied per age
% group so that the age distribution is captured directly.
monthlyCaseRSVUse = monthlyILICaseRSV(monthlyILICaseRSV.month_start<cutoffCOVID,:);
monthlyAgeSpecificIncidence = zeros(length(monthlyCaseRSVUse.year),numAgeGroups);
for iiMonth = 1:length(monthlyCaseRSVUse.year)
    monthlyAgeSpecificIncidence(iiMonth,:) = sum(outSEIR.stateZ((monthlyCaseRSVUse.month_start(iiMonth)/dt+1):(monthlyCaseRSVUse.month_end(iiMonth)/dt),:),1);
end
monthlyReport = monthlyAgeSpecificIncidence.*repmat(epsilonByAge,length(monthlyCaseRSVUse.year),1);
observedMonthlyCasesByAge = monthlyCaseRSVUse{:,{'adj_RSV_cases_0_4','adj_RSV_cases_5_19','adj_RSV_cases_20_49','adj_RSV_cases_50_64','adj_RSV_cases_65_above'}};
% Keep only a tiny numerical floor so the Thailand likelihood stays close
% to Poisson for low monthly counts.
meanFloorMonthlyReport = 1e-6;

% Find indices for monthly RSV data
[~, indicesMonthlyRSV] = ismember(ageDefMonthlyRSV, ageGroupDefRangeAll);
monthlyReportByAge = [...
    sum(monthlyReport(:,1:(indicesMonthlyRSV(1)-1)),2),...
    sum(monthlyReport(:,indicesMonthlyRSV(1):19),2)+monthlyReport(:,20)/10*5,...
    monthlyReport(:,20)/10*5+sum(monthlyReport(:,21),2)+monthlyReport(:,22)/10*5,...
    monthlyReport(:,22)/10*5+sum(monthlyReport(:,23),2),...
    sum(monthlyReport(:,24:(indicesMonthlyRSV(5)-1)),2)];
% Use a linear-dispersion negative binomial for sparse monthly counts,
% applied per age group. Under this parameterization Var(Y) = mu * (1 +
% linDispMonthlyReport).
logLikelihoodMonthlyReport = logNegativeBinomialMeanLinearDispersion(...
    observedMonthlyCasesByAge,...
    monthlyReportByAge,...
    linDispMonthlyReport,...
    meanFloorMonthlyReport);
logLikelihoodMonthlyReport(logLikelihoodMonthlyReport==-Inf) = -1e9;
logLikelihoodMonthlyReport(isnan(logLikelihoodMonthlyReport)) = -1e9;
% Age distribution is now captured by the per-age-group NB likelihood, so
% the separate multinomial component is no longer needed.
logLikelihoodMonthlyReportByAge = 0;

% Likelihood for RSV serology
seroTotalPopulation = (...
    outSEIR.stateM +...
    outSEIR.stateS0 + ...
    outSEIR.stateE0 + ...
    outSEIR.stateI0 + ...
    outSEIR.stateA0 + ...
    outSEIR.stateR0 + ...
    outSEIR.stateS1 + ...
    outSEIR.stateE1 + ...
    outSEIR.stateI1 + ...
    outSEIR.stateA1 + ...
    outSEIR.stateR1 + ...
    outSEIR.stateS2 + ...
    outSEIR.stateE2 + ...
    outSEIR.stateI2 + ...
    outSEIR.stateA2 + ...
    outSEIR.stateR2 + ...
    outSEIR.stateS3 + ...
    outSEIR.stateE3 + ...
    outSEIR.stateI3 + ...
    outSEIR.stateA3 + ...
    outSEIR.stateR3);
allStateR = (...
    outSEIR.stateM +...
    0*outSEIR.stateS0 + ...
    0*outSEIR.stateE0 + ...
    0*outSEIR.stateI0 + ...
    0*outSEIR.stateA0 + ...
    probSeropos*outSEIR.stateR0 + ...
    (1-delta1RelSuscep)*probSeropos*outSEIR.stateS1 + ...
    0*outSEIR.stateE1 + ...
    0*outSEIR.stateI1 + ...
    0*outSEIR.stateA1 + ...
    probSeropos*outSEIR.stateR1 + ...
    (1-delta2RelSuscep*delta1RelSuscep)*probSeropos*outSEIR.stateS2 + ...
    0*outSEIR.stateE2 + ...
    0*outSEIR.stateI2 + ...
    0*outSEIR.stateA2 + ...
    probSeropos*outSEIR.stateR2 + ...
    (1-delta3RelSuscep*delta2RelSuscep*delta1RelSuscep)*probSeropos*outSEIR.stateS3 + ...
    0*outSEIR.stateE3 + ...
    0*outSEIR.stateI3 + ...
    0*outSEIR.stateA3 + ...
    probSeropos*outSEIR.stateR3);

allStateM = outSEIR.pMaternalProtection;
allStateRPregnantWomen = sum(allStateR(:,indicesSeroPreg),2)./sum(seroTotalPopulation(:,indicesSeroPreg),2);
allStateRByAge = [allStateRPregnantWomen,allStateM,0.5*(allStateR(:,indicesSeroAge)./seroTotalPopulation(:,indicesSeroAge)+allStateR(:,indicesSeroAge)./seroTotalPopulation(:,indicesSeroAge))];

allStateRByAgeUse = allStateRByAge(cutoffCOVID/dt,:)';
allStateRByAgeUse(allStateRByAgeUse>1) = 1-1e-6;
logLikelihoodSeroprev = log(binopdf(seroprevData.num_seropos,seroprevData.num_samples,allStateRByAgeUse));
logLikelihoodSeroprev(logLikelihoodSeroprev==-Inf) = -1e9;
logLikelihoodSeroprev(isnan(logLikelihoodSeroprev)) = -1e9;


% Seroprevalence meta
allStateRMeta = zeros(length(allStateM),length(indicesSeroAgeMeta(:,1)));
for iiMeta = 1:length(indicesSeroAgeMeta(:,1))
    allStateRMeta(:,iiMeta) = sum(allStateR(:,indicesSeroAgeMeta(iiMeta,indicesSeroAgeMeta(iiMeta,:)>0)),2)./sum(seroTotalPopulation(:,indicesSeroAgeMeta(iiMeta,indicesSeroAgeMeta(iiMeta,:)>0)),2);
end
allStateRMetaUse = allStateRMeta(cutoffCOVID/dt,:)';
allStateRMetaUse(allStateRMetaUse>1) = 1-1e-6;
logLikelihoodSeroprevMeta = log(binopdf(seroprevDataMeta.N_positive,seroprevDataMeta.N,allStateRMetaUse));
logLikelihoodSeroprevMeta(logLikelihoodSeroprevMeta==-Inf) = -1e9;
logLikelihoodSeroprevMeta(isnan(logLikelihoodSeroprevMeta)) = -1e9;

% Seroprevalence HK rec 2020
allStateRHK = zeros(length(allStateM),length(indicesSeroAgeHK(:,1)));
for iiHK = 1:length(indicesSeroAgeHK(:,1))
    allStateRHK(:,iiHK) = sum(allStateR(:,indicesSeroAgeHK(iiHK,indicesSeroAgeHK(iiHK,:)>0)),2)./sum(seroTotalPopulation(:,indicesSeroAgeHK(iiHK,indicesSeroAgeHK(iiHK,:)>0)),2);
end
allStateRHKUse = allStateRHK(cutoffCOVID/dt,:)';
allStateRHKUse(allStateRHKUse>1) = 1-1e-6;
logLikelihoodSeroprevHK = log(binopdf(seroprevDataHKRec.num_IgG_positive,seroprevDataHKRec.num_samples,allStateRHKUse));
logLikelihoodSeroprevHK(logLikelihoodSeroprevHK==-Inf) = -1e9;
logLikelihoodSeroprevHK(isnan(logLikelihoodSeroprevHK)) = -1e9;

logLArr = [...
    sum(logLIncubation),...
    sum(logLInfectious),...
    sum(logLikelihoodMonthlyReport(:)),...
    sum(logLikelihoodMonthlyReportByAge),...
    sum(logLikelihoodSeroprev),...
    sum(logLikelihoodSeroprevMeta),...
    sum(logLikelihoodSeroprevHK)];

sumLogL = sum(logLArr);

end
