function [iPar,iiLogL] = mcmcParallelBlock(countryText,mcSteps,...
    monthlyILICaseRSV,ageDefMonthlyRSV,...
    seroprevData,indicesSeroPreg,indicesSeroAge,...
    seroprevDataMeta,indicesSeroAgeMeta,...
    seroprevDataHKRec,indicesSeroAgeHK,...
    dataPitzerIncubation, dataPitzerInfectious,...
    stateM,...
    stateS0, stateS1, stateS2, stateS3,...
    stateE0, stateE1, stateE2, stateE3,...
    stateI0, stateI1, stateI2, stateI3,...
    stateA0, stateA1, stateA2, stateA3,...
    stateR0, stateR1, stateR2, stateR3,...
    stateZ,...
    probVmAb, probVvax,...
    totalPopulation, ageGroupDefRangeAll, muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr, conversationContactMatr,...
    dateZero,dateStart,cutoffCOVID, numDays, numTimeSteps, dt,...
    parameters,parameterSteps,parameterStepFloor,lowerLimit,upperLimit,blockUpdateGroup,...
    proposalCov1415,proposalCov2021,proposalCov2326,proposalCov345,proposalCov678)

    goodMC = false;
    numWhileLoop = 0;
    numPars = length(parameters);
    checkpointEvery = max(1,floor(mcSteps/100));
    adaptUntil = max(checkpointEvery,floor(0.3*mcSteps));
    acceptLowTarget = 0.40;
    acceptHighTarget = 0.60;
    acceptLowFinal = 0.3;
    acceptHighFinal = 0.70;
    % proposalCov2021 and proposalCov2326 are now passed in from
    % main_Thailand.m (warm-started from reference chain if available).
    % They are overwritten by local estimates once tt >= 200.

    if ~iscell(blockUpdateGroup)
        blockUpdateGroupCell = cell(size(blockUpdateGroup,1),1);
        for iiBlock = 1:size(blockUpdateGroup,1)
            blockUpdateGroupCell{iiBlock} = blockUpdateGroup(iiBlock,1):blockUpdateGroup(iiBlock,2);
        end
        blockUpdateGroup = blockUpdateGroupCell;
    end

    while goodMC == false
        numWhileLoop = numWhileLoop+1;
        iPar = nan(mcSteps,numPars);
        iiLogL = nan(mcSteps,1);
        iiLogLArr = nan(mcSteps,7);
        nAcceptTotal = zeros(1,numPars);
        nAcceptWindow = zeros(1,numPars);
        lastCheckpoint = 0;

        parameterSteps = max(parameterSteps,parameterStepFloor);
        parameterSteps = min([parameterSteps;upperLimit-lowerLimit]);

        parameters_c = parameters;
        logPrior = logPriorDistribution(parameters_c);
        [sumLogL,logLArr] = calcMCMCTotalLogLikelihood(parameters_c,...
            monthlyILICaseRSV,ageDefMonthlyRSV,...
            seroprevData,indicesSeroPreg,indicesSeroAge,...
            seroprevDataMeta,indicesSeroAgeMeta,...
            seroprevDataHKRec,indicesSeroAgeHK,...
            dataPitzerIncubation, dataPitzerInfectious,...
            stateM,...
            stateS0, stateS1, stateS2, stateS3,...
            stateE0, stateE1, stateE2, stateE3,...
            stateI0, stateI1, stateI2, stateI3,...
            stateA0, stateA1, stateA2, stateA3,...
            stateR0, stateR1, stateR2, stateR3,...
            stateZ,...
            probVmAb, probVvax,...
            totalPopulation, ageGroupDefRangeAll, muBirthRate,populationSizeTable,populationSizeTableRev,...
            phyContactMatr, conversationContactMatr,...
            dateZero,dateStart,cutoffCOVID, numDays, numTimeSteps, dt);

        logLikelihood = logPrior+sumLogL;

        for tt = 1:mcSteps
            blockOrder = randperm(numel(blockUpdateGroup));
            for iiOrder = 1:numel(blockOrder)
                ii = blockOrder(iiOrder);
                parameters_mc = parameters_c;
                [tempNew,logProposalCorrection] = mcmcProposal(parameters_c,parameterSteps,lowerLimit,upperLimit,...
                    proposalCov1415,proposalCov2021,proposalCov2326,proposalCov345,proposalCov678);
                acceptIdx = blockUpdateGroup{ii};
                parameters_mc(acceptIdx) = tempNew(acceptIdx);
                if any(parameters_mc(acceptIdx) < lowerLimit(acceptIdx)) || ...
                        any(parameters_mc(acceptIdx) > upperLimit(acceptIdx)) || ...
                        any(parameterConstraint(parameters_mc)>0)
                    continue;
                end
                logPrior_new = logPriorDistribution(parameters_mc);
                [sumLogL_new,logLArr_new] = calcMCMCTotalLogLikelihood(parameters_mc,...
                    monthlyILICaseRSV,ageDefMonthlyRSV,...
                    seroprevData,indicesSeroPreg,indicesSeroAge,...
                    seroprevDataMeta,indicesSeroAgeMeta,...
                    seroprevDataHKRec,indicesSeroAgeHK,...
                    dataPitzerIncubation, dataPitzerInfectious,...
                    stateM,...
                    stateS0, stateS1, stateS2, stateS3,...
                    stateE0, stateE1, stateE2, stateE3,...
                    stateI0, stateI1, stateI2, stateI3,...
                    stateA0, stateA1, stateA2, stateA3,...
                    stateR0, stateR1, stateR2, stateR3,...
                    stateZ,...
                    probVmAb, probVvax,...
                    totalPopulation, ageGroupDefRangeAll, muBirthRate,populationSizeTable,populationSizeTableRev,...
                    phyContactMatr, conversationContactMatr,...
                    dateZero,dateStart,cutoffCOVID, numDays, numTimeSteps, dt);

                logLikelihood_new = logPrior_new + sumLogL_new;
                logAlpha = min(0,logLikelihood_new-logLikelihood + ...
                    sum(logProposalCorrection(acceptIdx)));
                alpha = exp(logAlpha);
                uu = rand;
                if uu <= alpha
                    parameters_c = parameters_mc;
                    logLikelihood = logLikelihood_new;
                    logLArr = logLArr_new;
                    nAcceptTotal(acceptIdx) = nAcceptTotal(acceptIdx)+1;
                    nAcceptWindow(acceptIdx) = nAcceptWindow(acceptIdx)+1;
                end
            end
            iiLogL(tt,:) = logLikelihood;
            iiLogLArr(tt,:) = logLArr;
            iPar(tt,:) = parameters_c;

            if mod(tt,checkpointEvery) == 0 || tt == mcSteps
                pAccept = nAcceptTotal/tt;

                if tt <= adaptUntil
                    windowCount = tt-lastCheckpoint;
                    pAcceptWindow = nAcceptWindow/max(windowCount,1);
                    parameterSteps(pAcceptWindow > acceptHighTarget) = parameterSteps(pAcceptWindow > acceptHighTarget)*1.2;
                    parameterSteps(pAcceptWindow < acceptLowTarget) = parameterSteps(pAcceptWindow < acceptLowTarget)/1.25;
                    parameterSteps = max(parameterSteps,parameterStepFloor);
                    parameterSteps = min([parameterSteps;upperLimit-lowerLimit]);

                    if tt >= 200
                        histStart = max(1,floor(0.5*tt));
                        histSamples = iPar(histStart:tt,:);
                        proposalCov1415 = calcCov1415(histSamples);
                        proposalCov2021 = calcCovBoundedPair(histSamples,lowerLimit,upperLimit,[20,21]);
                        proposalCov2326 = calcCovBoundedBlock(histSamples,lowerLimit,upperLimit,[23,24,25,26]);
                        proposalCov345 = calcCovBoundedBlock(histSamples,lowerLimit,upperLimit,[3,4,5]);
                        proposalCov678 = calcCovBoundedBlock(histSamples,lowerLimit,upperLimit,[6,7,8]);
                    end

                    nAcceptWindow(:) = 0;
                    lastCheckpoint = tt;
                end

                write_matrix_new(parameterSteps,strcat('mcmc_result/',countryText,'_parameter_step.csv'),'w',',','dec');
                write_matrix_new(iPar(1:tt,:),strcat('mcmc_result/',countryText,'_mcmc_res.csv'),'w',',','dec');
                write_matrix_new(iiLogL(1:tt,:),strcat('mcmc_result/',countryText,'_log_likelihood.csv'),'w',',','dec');
                write_matrix_new(iiLogLArr(1:tt,:),strcat('mcmc_result/',countryText,'_log_likelihood_component.csv'),'w',',','dec');
                disp('MCMC');
                display(tt/mcSteps);
                disp('Acceptance probability');
                display(pAccept);

                if any(pAccept > acceptHighFinal) || any(pAccept < acceptLowFinal)
                    goodMC = false;
                    if numWhileLoop < 10
                        if tt/mcSteps >= 0.02
                            continue;
                        end
                    else
                        goodMC = true;
                    end
                else
                    goodMC = true;
                end
            end
        end
    end
end
