function out = age_SEIR_RSV_intervention(...
    stateM,...
    stateS0, stateS1, stateS2, stateS3,...
    stateE0, stateE1, stateE2, stateE3,...
    stateI0, stateI1, stateI2, stateI3,...
    stateA0, stateA1, stateA2, stateA3,...
    stateR0, stateR1, stateR2, stateR3,...
    stateZ,...
    stateVmab1,stateVmab2,stateVmvax1,stateVmvax2,stateVpvax1,stateVpvax2,...
    mAbCoverage,~,mAbDuration,...
    mVaxCoverage,~,mVaxDuration,...
    oVaxCoverage,~,oVaxDuration,...
    totalPopulation, ageGroupDefRangeAll, muBirthRate,populationSizeTable,populationSizeTableRev,...
    phyContactMatr, conversationContactMatr,...
    iniInfectiousProp, iniRecoveredProp,...
    ~, dateStart, numDays, numTimeSteps, dt,...
    xiMaternalImmunity, omegaInfectionImmunity, sigmaExposure,...
    gammaZeroPrimaryInfection, g1ReductionInfectiousDuration, g2ReductionInfectiousDuration,...
    delta1RelSuscep, delta2RelSuscep, delta3RelSuscep,...
    pAsym, alphaReductionInfectiousness,...
    qTransmissPhysical, qTransmissConversation,...
    b1AmpTransmissPeak, phiSeasonalShift, psiSeasonalWavelength,probSeropos) %#codegen
    
    % Initialize parameters
    numAgeGroups = length(ageGroupDefRangeAll)-1;
    iniInfectiousL1 = iniInfectiousProp*ones(1,numAgeGroups);
    iniRecoveredL2 = iniRecoveredProp*ones(1,numAgeGroups);
    [stateM,...
        stateS0, stateS1, stateS2, stateS3,...
        stateE0, stateE1, stateE2, stateE3,...
        stateI0, stateI1, stateI2, stateI3,...
        stateA0, stateA1, stateA2, stateA3,...
        stateR0, stateR1, stateR2, stateR3,...
        stateVmab1,stateVmab2,...
        stateVmvax1,stateVmvax2,...
        stateVpvax1,stateVpvax2,...
        pAsym_arr] = age_SEIR_initial_conditions_intervention(...
        stateM,...
        stateS0, stateS1, stateS2, stateS3,...
        stateE0, stateE1, stateE2, stateE3,...
        stateI0, stateI1, stateI2, stateI3,...
        stateA0, stateA1, stateA2, stateA3,...
        stateR0, stateR1, stateR2, stateR3,...
        stateVmab1,stateVmab2,...
        stateVmvax1,stateVmvax2,...
        stateVpvax1,stateVpvax2,...
        totalPopulation, ageGroupDefRangeAll,...
        iniInfectiousL1, iniRecoveredL2,...
        xiMaternalImmunity, sigmaExposure,...
        gammaZeroPrimaryInfection, g1ReductionInfectiousDuration, g2ReductionInfectiousDuration,...
        delta1RelSuscep, delta2RelSuscep, delta3RelSuscep,...
        pAsym,...
        mAbCoverage,mVaxCoverage,oVaxCoverage);
    
    % Indicator function for new births
    muBirthIndicator = zeros(size(totalPopulation));
    muBirthIndicator(1) = 1;
    % Indicator matrix for aging
    agingIndicator = ones(size(totalPopulation));
    agingIndicator(1) = 0;

    % Aging and mortality
    [agingRate,etaMortalityRate] = calcAgingRate(populationSizeTable,populationSizeTableRev,ageGroupDefRangeAll);
    dailyMortalityByAge = (agingRate(1+round((ageGroupDefRangeAll(1:(end-1))+ageGroupDefRangeAll(2:end))/2*12))/365.25*12)';
    dailyMortalityByAge(end) = ...
        populationSizeTable.population_count((end-2):end)'*...
        agingRate(populationSizeTable.age_group_end((end-2):end)*12)/sum(populationSizeTable.population_count((end-2):end))/365.25*12;
    % Rate of vaccination
    oVaxCoverageRateInitial = oVaxCoverage/180;

    % Rt
    refRt = zeros(numTimeSteps,1);
    pMaternalProtectionRec = zeros(numTimeSteps,1);

    % Main loop over time steps
    for tStep = 1:(numTimeSteps - 1)
        % Calculate population adjustment BEFORE updating states
        checkTotalPopulationCurrent = [...
            stateM(tStep, :);...
            stateVmab1(tStep, :);...
            stateVmab2(tStep, :);...
            stateVmvax1(tStep, :);...
            stateVmvax2(tStep, :);...
            stateS0(tStep, :);...
            stateE0(tStep, :);...
            stateA0(tStep, :);...
            stateI0(tStep, :);...
            stateR0(tStep, :);...
            stateS1(tStep, :);...
            stateE1(tStep, :);...
            stateA1(tStep, :);...
            stateI1(tStep, :);...
            stateR1(tStep, :);...
            stateS2(tStep, :);...
            stateE2(tStep, :);...
            stateA2(tStep, :);...
            stateI2(tStep, :);...
            stateR2(tStep, :);...
            stateS3(tStep, :);...
            stateVpvax1(tStep, :);...
            stateVpvax2(tStep, :);...
            stateE3(tStep, :);...
            stateA3(tStep, :);...
            stateI3(tStep, :);...
            stateR3(tStep, :);];

        % Check older adult vax coverage
        checkOlderVaxCoverage = (stateVpvax1(tStep, :)+stateVpvax2(tStep, :))./sum(checkTotalPopulationCurrent,1);
        oVaxCoverageRate = zeros(size(oVaxCoverageRateInitial));
        oVaxCoverageRate(checkOlderVaxCoverage<oVaxCoverage) = oVaxCoverageRateInitial(checkOlderVaxCoverage<oVaxCoverage);
        
        reductionPopulation = ...
            dt*(muBirthRate(1)- ...
            sum(checkTotalPopulationCurrent(:,end),1)*etaMortalityRate(end)- ...
            sum(checkTotalPopulationCurrent,1)*dailyMortalityByAge');
        
        % Adjust for population reduction
        numStates = 27;
        tempAging = checkTotalPopulationCurrent.*repmat([ones(1,22),0,0,0],numStates,1);
        reductionPopulationPerc = -reductionPopulation/sum(sum(tempAging))*tempAging;

        % Calculate force of infection
        lambda_no_deltaSusp = zeros(1, numAgeGroups);
        for iiAge = 1:numAgeGroups
            % Calculate the force of infection using the contact matrices and current state
            sumInfections = 0;
            for jjAge = 1:numAgeGroups
                sumInfections = sumInfections + ...
                    (phyContactMatr(iiAge, jjAge) + qTransmissConversation * conversationContactMatr(iiAge, jjAge)) *...
                    (stateA0(tStep, jjAge) * alphaReductionInfectiousness + stateI0(tStep, jjAge) + ...
                     stateA1(tStep, jjAge) * alphaReductionInfectiousness + stateI1(tStep, jjAge) + ...
                     stateA2(tStep, jjAge) * alphaReductionInfectiousness + stateI2(tStep, jjAge) + ...
                     stateA3(tStep, jjAge) * alphaReductionInfectiousness + stateI3(tStep, jjAge));
            end
            lambda_no_deltaSusp(iiAge) = qTransmissPhysical * ...
                (1 + b1AmpTransmissPeak * exp((mod(dateStart + tStep*dt,365.25)/365.25 - phiSeasonalShift)^2 / (2 * psiSeasonalWavelength^2))) * ...
                sumInfections;
        end

        tempRt = lambda_no_deltaSusp./(...
            1/gammaZeroPrimaryInfection*stateA0(tStep, :) + 1/gammaZeroPrimaryInfection*stateI0(tStep, :) + ...
            1/(gammaZeroPrimaryInfection / g1ReductionInfectiousDuration)*stateA1(tStep, :) + 1/(gammaZeroPrimaryInfection / g1ReductionInfectiousDuration)*stateI1(tStep, :) + ...
            1/(gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration)*stateA2(tStep, :) + 1/(gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration)*stateI2(tStep, :) + ...
            1/(gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration)*stateA3(tStep, :) + 1/(gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration)*stateI3(tStep, :));
        refRt(tStep,1) = tempRt*totalPopulation';

        % Update each state variable using the ODEs
        % Combining mAb and maternal protection, assuming all mothers are 25-44
        pMaternalProtection = sum((...
            stateM(tStep,20:21) + ...
            stateVmab1(tStep,20:21) + ...
            stateVmab2(tStep,20:21) + ...
            stateVmvax1(tStep,20:21) + ...
            stateVmvax2(tStep,20:21) + ...
            0*stateS0(tStep,20:21) + ...
            0*stateE0(tStep,20:21) + ...
            0*stateI0(tStep,20:21) + ...
            0*stateA0(tStep,20:21) + ...
            probSeropos*stateR0(tStep,20:21) + ...
            (1-delta1RelSuscep)*probSeropos*stateS1(tStep,20:21) + ...
            0*stateE1(tStep,20:21) + ...
            0*stateI1(tStep,20:21) + ...
            0*stateA1(tStep,20:21) + ....
            probSeropos*stateR1(tStep,20:21) + ...
            (1-delta2RelSuscep*delta1RelSuscep)*probSeropos*stateS2(tStep,20:21) + ...
            0*stateE2(tStep,20:21) + ...
            0*stateI2(tStep,20:21) + ...
            0*stateA2(tStep,20:21) + ...
            probSeropos*stateR2(tStep,20:21) + ...
            (1-delta3RelSuscep*delta2RelSuscep*delta1RelSuscep)*stateS3(tStep,20:21) + ...
            stateVpvax1(tStep,20:21) + ...
            stateVpvax2(tStep,20:21) +...
            0*stateE3(tStep,20:21) + ...
            0*stateI3(tStep,20:21) + ...
            0*stateA3(tStep,20:21) + ...
            probSeropos*stateR3(tStep,20:21) ))/sum(totalPopulation(20:21));

        pMaternalProtectionRec(tStep,1) = pMaternalProtection;
        
        % Maternal protected
        stateM(tStep + 1, :) = reductionPopulationPerc(1,:) + stateM(tStep, :) + ...
            ((1-mAbCoverage-mVaxCoverage).*(pMaternalProtection.*(muBirthRate(1).* muBirthIndicator))- xiMaternalImmunity * stateM(tStep, :) - ...
            etaMortalityRate.* stateM(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateM(tStep, 1:(end-1))].*agingIndicator-...
            stateM(tStep, :).*dailyMortalityByAge) * dt;
        % mAb
        stateVmab1(tStep + 1, :)  = reductionPopulationPerc(2,:) + stateVmab1(tStep, :) + ...
            ((mAbCoverage).*((muBirthRate(1).* muBirthIndicator)) - 1/(mAbDuration/2) * stateVmab1(tStep, :) - ...
            etaMortalityRate.* stateVmab1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateVmab1(tStep, 1:(end-1))].*agingIndicator-...
            stateVmab1(tStep, :).*dailyMortalityByAge) * dt;
        stateVmab2(tStep + 1, :)  = reductionPopulationPerc(3,:) + stateVmab2(tStep, :) + ...
            (1/(mAbDuration/2) * stateVmab1(tStep, :)  - 1/(mAbDuration/2) * stateVmab2(tStep, :) - ...
            etaMortalityRate.* stateVmab2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateVmab2(tStep, 1:(end-1))].*agingIndicator-...
            stateVmab2(tStep, :).*dailyMortalityByAge) * dt;
        % Maternal vaccination
        stateVmvax1(tStep + 1, :)  = reductionPopulationPerc(4,:) + stateVmvax1(tStep, :) + ...
            ((mVaxCoverage).*((muBirthRate(1).* muBirthIndicator)) - 1/(mVaxDuration/2) * stateVmvax1(tStep, :) - ...
            etaMortalityRate.* stateVmvax1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateVmvax1(tStep, 1:(end-1))].*agingIndicator-...
            stateVmvax1(tStep, :).*dailyMortalityByAge) * dt;
        stateVmvax2(tStep + 1, :)  = reductionPopulationPerc(5,:) + stateVmvax2(tStep, :) + ...
            (1/(mVaxDuration/2) * stateVmvax1(tStep, :)  - 1/(mVaxDuration/2) * stateVmvax2(tStep, :) - ...
            etaMortalityRate.* stateVmvax2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateVmvax2(tStep, 1:(end-1))].*agingIndicator-...
            stateVmvax2(tStep, :).*dailyMortalityByAge) * dt;

        % States
        stateS0(tStep + 1, :) = reductionPopulationPerc(6,:) +  stateS0(tStep, :) + ...
            (((1-mAbCoverage-mVaxCoverage).*(1-pMaternalProtection)).*(muBirthRate(1).* muBirthIndicator) + ...
            xiMaternalImmunity * stateM(tStep, :) +...
            1/(mAbDuration/2) * stateVmab2(tStep, :) +...
            1/(mVaxDuration/2) * stateVmvax2(tStep, :) - ...
            lambda_no_deltaSusp .* stateS0(tStep, :) - ...
            etaMortalityRate.* stateS0(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateS0(tStep, 1:(end-1))].*agingIndicator-...
            stateS0(tStep, :).*dailyMortalityByAge) * dt;

        stateE0(tStep + 1, :) = reductionPopulationPerc(7,:) +  stateE0(tStep, :) + ...
            (lambda_no_deltaSusp .* stateS0(tStep, :) - sigmaExposure * stateE0(tStep, :) - ...
             etaMortalityRate.* stateE0(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateE0(tStep, 1:(end-1))].*agingIndicator-...
            stateE0(tStep, :).*dailyMortalityByAge) * dt;

        stateA0(tStep + 1, :) = reductionPopulationPerc(8,:) +  stateA0(tStep, :) + ...
            (sigmaExposure * pAsym_arr.* stateE0(tStep, :) - gammaZeroPrimaryInfection * stateA0(tStep, :) - ...
              etaMortalityRate.* stateA0(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateA0(tStep, 1:(end-1))].*agingIndicator-...
             stateA0(tStep, :).*dailyMortalityByAge) * dt;

        stateI0(tStep + 1, :) = reductionPopulationPerc(9,:) +  stateI0(tStep, :) + ...
            (sigmaExposure * (1 - pAsym_arr).* stateE0(tStep, :) - gammaZeroPrimaryInfection * stateI0(tStep, :) - ...
              etaMortalityRate.* stateI0(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateI0(tStep, 1:(end-1))].*agingIndicator-...
             stateI0(tStep, :).*dailyMortalityByAge) * dt;

        stateR0(tStep + 1, :) = reductionPopulationPerc(10,:) +  stateR0(tStep, :) + ...
            (gammaZeroPrimaryInfection * (stateA0(tStep, :) + stateI0(tStep, :)) - omegaInfectionImmunity * stateR0(tStep, :) - ...
              etaMortalityRate.* stateR0(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateR0(tStep, 1:(end-1))].*agingIndicator-...
             stateR0(tStep, :).*dailyMortalityByAge) * dt;

        stateS1(tStep + 1, :) = reductionPopulationPerc(11,:) +  stateS1(tStep, :) + ...
            (omegaInfectionImmunity * stateR0(tStep, :) - delta1RelSuscep * lambda_no_deltaSusp .* stateS1(tStep, :) - ...
             etaMortalityRate.* stateS1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateS1(tStep, 1:(end-1))].*agingIndicator-...
             stateS1(tStep, :).*dailyMortalityByAge) * dt;

        stateE1(tStep + 1, :) = reductionPopulationPerc(12,:) +  stateE1(tStep, :) + ...
            (delta1RelSuscep * lambda_no_deltaSusp .* stateS1(tStep, :) - sigmaExposure * stateE1(tStep, :) - ...
              etaMortalityRate.* stateE1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateE1(tStep, 1:(end-1))].*agingIndicator-...
             stateE1(tStep, :).*dailyMortalityByAge) * dt;

        stateA1(tStep + 1, :) = reductionPopulationPerc(13,:) +  stateA1(tStep, :) + ...
            (sigmaExposure * pAsym_arr.* stateE1(tStep, :) - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration * stateA1(tStep, :) - ...
             etaMortalityRate.* stateA1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateA1(tStep, 1:(end-1))].*agingIndicator-...
             stateA1(tStep, :).*dailyMortalityByAge) * dt;

        stateI1(tStep + 1, :) = reductionPopulationPerc(14,:) +  stateI1(tStep, :) + ...
            (sigmaExposure * (1 - pAsym_arr).* stateE1(tStep, :) - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration * stateI1(tStep, :) - ...
              etaMortalityRate.* stateI1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateI1(tStep, 1:(end-1))].*agingIndicator-...
             stateI1(tStep, :).*dailyMortalityByAge) * dt;

        stateR1(tStep + 1, :) = reductionPopulationPerc(15,:) +  stateR1(tStep, :) + ...
            (gammaZeroPrimaryInfection / g1ReductionInfectiousDuration * (stateA1(tStep, :) + stateI1(tStep, :)) - omegaInfectionImmunity * stateR1(tStep, :) - ...
             etaMortalityRate.* stateR1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateR1(tStep, 1:(end-1))].*agingIndicator-...
            stateR1(tStep, :).*dailyMortalityByAge) * dt;

        % Similar updates for stateS2, stateE2, stateA2, stateI2, stateR2
        % Similar updates for stateS3, stateE3, stateA3, stateI3, stateR3
        % Update stateS2, stateE2, stateA2, stateI2, stateR2
        stateS2(tStep + 1, :) = reductionPopulationPerc(16,:) +  stateS2(tStep, :) + ...
            (omegaInfectionImmunity * stateR1(tStep, :) - delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS2(tStep, :) - ...
              etaMortalityRate.* stateS2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateS2(tStep, 1:(end-1))].*agingIndicator-...
             stateS2(tStep, :).*dailyMortalityByAge) * dt;

        stateE2(tStep + 1, :) = reductionPopulationPerc(17,:) +  stateE2(tStep, :) + ...
            (delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS2(tStep, :) - sigmaExposure * stateE2(tStep, :) - ...
              etaMortalityRate.* stateE2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateE2(tStep, 1:(end-1))].*agingIndicator-...
             stateE2(tStep, :).*dailyMortalityByAge)* dt;

        stateA2(tStep + 1, :) = reductionPopulationPerc(18,:) +  stateA2(tStep, :) + ...
            (sigmaExposure * pAsym_arr.* stateE2(tStep, :) - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateA2(tStep, :) - ...
              etaMortalityRate.* stateA2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateA2(tStep, 1:(end-1))].*agingIndicator-...
             stateA2(tStep, :).*dailyMortalityByAge) * dt;

        stateI2(tStep + 1, :) = reductionPopulationPerc(19,:) +  stateI2(tStep, :) + ...
            (sigmaExposure * (1 - pAsym_arr).* stateE2(tStep, :) - gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateI2(tStep, :) - ...
              etaMortalityRate.* stateI2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateI2(tStep, 1:(end-1))].*agingIndicator-...
             stateI2(tStep, :).*dailyMortalityByAge) * dt;

        stateR2(tStep + 1, :) = reductionPopulationPerc(20,:) +  stateR2(tStep, :) + ...
            (gammaZeroPrimaryInfection / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * (stateA2(tStep, :) + stateI2(tStep, :)) - omegaInfectionImmunity * stateR2(tStep, :) - ...
             etaMortalityRate.* stateR2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateR2(tStep, 1:(end-1))].*agingIndicator-...
            stateR2(tStep, :).*dailyMortalityByAge) * dt;

        % Update stateS3, stateE3, stateA3, stateI3, stateR3
        % Vaccination to stateS3 only
        stateS3(tStep + 1, :) = reductionPopulationPerc(21,:) +  stateS3(tStep, :) + ...
            (omegaInfectionImmunity * stateR2(tStep, :) + ... % from R2 to S3
             omegaInfectionImmunity * stateR3(tStep, :) - ... % from R3 back to S3
             oVaxCoverageRate.*stateS3(tStep, :) + ...         % vaccination to stateVpvax1
             1/(oVaxDuration/2)*stateVpvax2(tStep, :) - ...     % waning from stateVpvax2 to S3
             delta3RelSuscep * delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS3(tStep, :) - ... % infection
             etaMortalityRate.* stateS3(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateS3(tStep, 1:(end-1))].*agingIndicator-... % aging
             stateS3(tStep, :).*dailyMortalityByAge) * dt;

        stateVpvax1(tStep + 1, :) = reductionPopulationPerc(22,:) +  stateVpvax1(tStep, :) + ...
            (oVaxCoverageRate.*stateS3(tStep, :) - ...      % from S3 to stateVpvax1
             1/(oVaxDuration/2)*stateVpvax1(tStep, :) - ... % from stateVpvax1 to stateVpvax2
             etaMortalityRate.* stateVpvax1(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateVpvax1(tStep, 1:(end-1))].*agingIndicator-... % aging
             stateVpvax1(tStep, :).*dailyMortalityByAge) * dt;
        
        stateVpvax2(tStep + 1, :) = reductionPopulationPerc(23,:) +  stateVpvax2(tStep, :) + ...
            (1/(oVaxDuration/2)*stateVpvax1(tStep, :) - ... % from stateVpvax1 to stateVpvax2
             1/(oVaxDuration/2)*stateVpvax2(tStep, :) - ... % waning from stateVpvax2 to S3
             etaMortalityRate.* stateVpvax2(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateVpvax2(tStep, 1:(end-1))].*agingIndicator-...    % aging
             stateVpvax2(tStep, :).*dailyMortalityByAge) * dt;     

        stateE3(tStep + 1, :) = reductionPopulationPerc(24,:) +  stateE3(tStep, :) + ...
            (delta3RelSuscep * delta2RelSuscep * delta1RelSuscep * lambda_no_deltaSusp .* stateS3(tStep, :) - ... 
             sigmaExposure * stateE3(tStep, :) - ... % from E3 to I3
             etaMortalityRate.* stateE3(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateE3(tStep, 1:(end-1))].*agingIndicator-...
             stateE3(tStep, :).*dailyMortalityByAge) * dt;

        stateA3(tStep + 1, :) = reductionPopulationPerc(25,:) +  stateA3(tStep, :) + ...
            (sigmaExposure * pAsym_arr.* stateE3(tStep, :) - gammaZeroPrimaryInfection  / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateA3(tStep, :) - ...
             etaMortalityRate.* stateA3(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateA3(tStep, 1:(end-1))].*agingIndicator-...
             stateA3(tStep, :).*dailyMortalityByAge) * dt;

        stateI3(tStep + 1, :) = reductionPopulationPerc(26,:) +  stateI3(tStep, :) + ...
            (sigmaExposure * (1 - pAsym_arr).* stateE3(tStep, :) - gammaZeroPrimaryInfection  / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * stateI3(tStep, :) - ...
             etaMortalityRate.* stateI3(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateI3(tStep, 1:(end-1))].*agingIndicator-...
             stateI3(tStep, :).*dailyMortalityByAge) * dt;

        stateR3(tStep + 1, :) = reductionPopulationPerc(27,:) +  stateR3(tStep, :) + ...
            (gammaZeroPrimaryInfection  / g1ReductionInfectiousDuration / g2ReductionInfectiousDuration * (stateA3(tStep, :) + stateI3(tStep, :)) - omegaInfectionImmunity * stateR3(tStep, :) - ...
            etaMortalityRate.* stateR3(tStep, :) + [0,etaMortalityRate(1:(end-1)).* stateR3(tStep, 1:(end-1))].*agingIndicator-...
            stateR3(tStep, :).*dailyMortalityByAge) * dt;

        % Calculate cumulative infections
        stateZ(tStep + 1, :) = sigmaExposure * (stateE0(tStep, :) + stateE1(tStep, :) + ...
            stateE2(tStep, :) + stateE3(tStep, :)) * dt;

        % Update interventions (stateVmAb and stateVvax)
        % These would require additional logic based on your specific intervention strategies

        % % Adjust for population reduction
        % checkTotalPopulation = zeros(numStates,numAgeGroups,2);
        % 
        % checkTotalPopulation(:,:,1) = [...
        %     stateM(tStep, :);...
        %     stateS0(tStep, :);...
        %     stateE0(tStep, :);...
        %     stateA0(tStep, :);...
        %     stateI0(tStep, :);...
        %     stateR0(tStep, :);...
        %     stateS1(tStep, :);...
        %     stateE1(tStep, :);...
        %     stateA1(tStep, :);...
        %     stateI1(tStep, :);...
        %     stateR1(tStep, :);...
        %     stateS2(tStep, :);...
        %     stateE2(tStep, :);...
        %     stateA2(tStep, :);...
        %     stateI2(tStep, :);...
        %     stateR2(tStep, :);...
        %     stateS3(tStep, :);...
        %     stateE3(tStep, :);...
        %     stateA3(tStep, :);...
        %     stateI3(tStep, :);...
        %     stateR3(tStep, :);...
        %     stateVmab1(tStep, :);...
        %     stateVmab2(tStep, :);...
        %     stateVmvax1(tStep, :);...
        %     stateVmvax2(tStep, :);...
        %     stateVpvax1(tStep, :);...
        %     stateVpvax2(tStep, :);];
        % 
        % checkTotalPopulation(:,:,2) = [...
        %     stateM(tStep+1, :);...
        %     stateS0(tStep+1, :);...
        %     stateE0(tStep+1, :);...
        %     stateA0(tStep+1, :);...
        %     stateI0(tStep+1, :);...
        %     stateR0(tStep+1, :);...
        %     stateS1(tStep+1, :);...
        %     stateE1(tStep+1, :);...
        %     stateA1(tStep+1, :);...
        %     stateI1(tStep+1, :);...
        %     stateR1(tStep+1, :);...
        %     stateS2(tStep+1, :);...
        %     stateE2(tStep+1, :);...
        %     stateA2(tStep+1, :);...
        %     stateI2(tStep+1, :);...
        %     stateR2(tStep+1, :);...
        %     stateS3(tStep+1, :);...
        %     stateE3(tStep+1, :);...
        %     stateA3(tStep+1, :);...
        %     stateI3(tStep+1, :);...
        %     stateR3(tStep+1, :);...
        %     stateVmab1(tStep+1, :);...
        %     stateVmab2(tStep+1, :);...
        %     stateVmvax1(tStep+1, :);...
        %     stateVmvax2(tStep+1, :);...
        %     stateVpvax1(tStep+1, :);...
        %     stateVpvax2(tStep+1, :);];

        % disp(sum(sum(checkTotalPopulation(:,:,2)))-sum(sum(checkTotalPopulation(:,:,1))))
      
    end

    out = struct();
    out.timeVec = 0:dt:numDays;
    out.Rt = refRt;
    out.pMaternalProtection = pMaternalProtectionRec;
    out.stateM = stateM;
    out.stateS0 = stateS0;
    out.stateS1 = stateS1;
    out.stateS2 = stateS2;
    out.stateS3 = stateS3;
    out.stateE0 = stateE0;
    out.stateE1 = stateE1;
    out.stateE2 = stateE2;
    out.stateE3 = stateE3;
    out.stateI0 = stateI0;
    out.stateI1 = stateI1;
    out.stateI2 = stateI2;
    out.stateI3 = stateI3;
    out.stateA0 = stateA0;
    out.stateA1 = stateA1;
    out.stateA2 = stateA2;
    out.stateA3 = stateA3;
    out.stateR0 = stateR0;
    out.stateR1 = stateR1;
    out.stateR2 = stateR2;
    out.stateR3 = stateR3;
    out.stateZ = stateZ;
    out.stateVmab1 = stateVmab1;
    out.stateVmab2 = stateVmab2;
    out.stateVmvax1 = stateVmvax1;
    out.stateVmvax2 = stateVmvax2;
    out.stateVpvax1 = stateVpvax1;
    out.stateVpvax2 = stateVpvax2;
    
end